name: Run Selenium TestNG Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
      GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
      GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Java 11 (Temurin)
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Chrome + ChromeDriver (Ubuntu runner needs this)
      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1

      - name: Verify Chrome Installation
        run: |
          google-chrome --version
          chromedriver --version

      # Build the project
      - name: Install dependencies
        run: mvn clean install -DskipTests

      # Run TestNG Tests
      - name: Run Tests
        run: mvn test

      # Upload reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: target/surefire-reports
